sonar.projectKey=REMS1
sonar.working.directory=C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API
sonar.pullrequest.cache.basepath=C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API
sonar.sources=\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.vs\\ProjectSettings.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.vs\\VSWorkspaceState.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.vs\\REMS.API.slnx\\v18\\DocumentLayout.backup.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.vs\\REMS.API.slnx\\v18\\DocumentLayout.json"

C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.projectKey=REMS1:C2221FDD-F1CB-996D-3136-1ED87DBE39CC
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.projectName=REMS.API
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.projectBaseDir=C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.sourceEncoding=utf-8
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.tests=
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.sources=\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Controllers\\GirisController.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Controllers\\IlceController.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Controllers\\IlController.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Controllers\\KullaniciController.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Controllers\\MahalleController.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Controllers\\TasinmazController.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Data\\RemsDbContext.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Giris\\LoginDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Ilce\\IlceListDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Il\\IlListDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Kullanici\\KullaniciListDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Mahalle\\MahalleListDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Tasinmaz\\TasinmazCreateDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Tasinmaz\\TasinmazListDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\DTOs\\Tasinmaz\\TasinmazUpdateDto.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Entities\\Il.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Entities\\Ilce.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Entities\\Kullanici.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Entities\\Mahalle.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Entities\\Tasinmaz.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Interfaces\\IGirisService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Interfaces\\IIlceService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Interfaces\\IIlService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Interfaces\\IKullaniciService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Interfaces\\ITasinmazService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Interfaces\\MahalleService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Migrations\\20260812131441_IlkTablolar.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Migrations\\20260812131441_IlkTablolar.Designer.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Migrations\\RemsDbContextModelSnapshot.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Program.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\GirisService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\HashService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\IlceService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\IlService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\KullaniciService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\MahalleService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Services\\TasinmazService.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\REMS.API.GlobalUsings.g.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\REMS.API.AssemblyInfo.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\REMS.API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\appsettings.Development.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\appsettings.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\REMS.API.http",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\Properties\\launchSettings.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\project.assets.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\REMS.API.csproj.nuget.dgspec.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\bin\\Debug\\net8.0\\REMS.API.deps.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\bin\\Debug\\net8.0\\REMS.API.runtimeconfig.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\bin\\Debug\\net8.0\\REMS.API.staticwebassets.endpoints.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\REMS.API.sourcelink.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\REMS.API\\obj\\Debug\\net8.0\\EndpointInfo\\REMS.API.json"

C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.sonarqube\\out\\0"
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.sonarqube\\out\\0\\Issues.json"
C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.cs.scanner.telemetry=\
"C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.sonarqube\\out\\0\\Telemetry.json"

C2221FDD-F1CB-996D-3136-1ED87DBE39CC.sonar.working.directory=C:\\Users\\Esra\\Desktop\\Esra\\Projects\\OdakGIS_Staj\\REMS\\REMS.API\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=C2221FDD-F1CB-996D-3136-1ED87DBE39CC

