// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using REMS.API.Data;

#nullable disable

namespace REMS.API.Migrations
{
    [DbContext(typeof(RemsDbContext))]
    [Migration("20260814071211_LokasyonVerileriEklendi")]
    partial class LokasyonVerileriEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("REMS.API.Entities.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Iller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Ankara"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "İstanbul"
                        });
                });

            modelBuilder.Entity("REMS.API.Entities.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IlId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Çankaya",
                            IlId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Yenimahalle",
                            IlId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Kadıköy",
                            IlId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Beşiktaş",
                            IlId = 2
                        });
                });

            modelBuilder.Entity("REMS.API.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            AdSoyad = "Sistem Yöneticisi",
                            AktifMi = true,
                            Email = "admin@rems.com",
                            OlusturmaTarihi = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rol = "Admin",
                            SifreHash = "ornek_hash",
                            SifreSalt = "ornek_salt"
                        });
                });

            modelBuilder.Entity("REMS.API.Entities.Mahalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IlceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IlceId");

                    b.ToTable("Mahalleler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kavaklıdere Mahallesi",
                            IlceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Bahçelievler Mahallesi",
                            IlceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Batıkent Mahallesi",
                            IlceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Caferağa Mahallesi",
                            IlceId = 3
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Moda Mahallesi",
                            IlceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Bebek Mahallesi",
                            IlceId = 4
                        });
                });

            modelBuilder.Entity("REMS.API.Entities.Tasinmaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdaNo")
                        .HasColumnType("text")
                        .HasColumnName("ada_no");

                    b.Property<string>("Adres")
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<decimal?>("AlanM2")
                        .HasColumnType("numeric")
                        .HasColumnName("alan_m2");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("text")
                        .HasColumnName("kullanici_id");

                    b.Property<int>("MahalleId")
                        .HasColumnType("integer")
                        .HasColumnName("mahalle_id");

                    b.Property<string>("ParselNo")
                        .HasColumnType("text")
                        .HasColumnName("parsel_no");

                    b.Property<Polygon>("Sinir")
                        .HasColumnType("geometry")
                        .HasColumnName("sinir");

                    b.Property<string>("TasinmazTipi")
                        .HasColumnType("text")
                        .HasColumnName("tasinmaz_tipi");

                    b.HasKey("Id");

                    b.ToTable("Tasinmazlar");
                });

            modelBuilder.Entity("REMS.API.Entities.Ilce", b =>
                {
                    b.HasOne("REMS.API.Entities.Il", "Il")
                        .WithMany("Ilceler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("REMS.API.Entities.Mahalle", b =>
                {
                    b.HasOne("REMS.API.Entities.Ilce", "Ilce")
                        .WithMany("Mahalleler")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("REMS.API.Entities.Il", b =>
                {
                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("REMS.API.Entities.Ilce", b =>
                {
                    b.Navigation("Mahalleler");
                });
#pragma warning restore 612, 618
        }
    }
}
